### ISSUE TITLE
Errors occurred when installing

### ISSUE THREAD

**Issue by xieduo7** [BIMIB-DISCo/J-Space.jl#3]
I posted the commands and logs below:

```
/data/xieduo/software/J-Space.jl
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.3 (2022-05-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> activate .
ERROR: syntax: space before "." not allowed in "activate ." at REPL[1]:1
Stacktrace:
 [1] top-level scope
   @ none:1

(@v1.7) pkg> activate .
  Activating project at `/data/xieduo/software/J-Space.jl`

(J_Space) pkg> instantiate
┌ Warning: The active manifest file is an older format with no julia version entry. Dependencies may have been resolved with a different julia version.
└ @ /data/xieduo/software/J-Space.jl/Manifest.toml:0
   Installed ImageIO ────────────── v0.5.9
   Installed BioGenerics ────────── v0.1.1
   Installed PNGFiles ───────────── v0.3.16
   Installed TiffImages ─────────── v0.5.5
   Installed MutableArithmetics ─── v1.0.2
   Installed OffsetArrays ───────── v1.11.0
   Installed GraphMakie ─────────── v0.3.0
   Installed PDMats ─────────────── v0.11.10
   Installed OpenEXR ────────────── v0.3.2
   Installed ModernGL ───────────── v1.1.4
   Installed NetworkLayout ──────── v0.4.3
   Installed GLMakie ────────────── v0.4.7
   Installed StaticArrays ───────── v1.4.4
   Installed CEnum ──────────────── v0.4.2
   Installed GLM ────────────────── v1.7.0
   Installed MetaGraphs ─────────── v0.7.1
   Installed Netpbm ─────────────── v1.0.2
   Installed BioSequences ───────── v2.0.5
   Installed SignedDistanceFields ─ v0.4.0
   Installed Static ─────────────── v0.6.4
   Installed EllipsisNotation ───── v1.5.1
   Installed JLD2 ───────────────── v0.4.22
   Installed FileIO ─────────────── v1.14.0
   Installed DataFrames ─────────── v1.3.0
   Installed ScanByte ───────────── v0.3.0
   Installed SIMD ───────────────── v3.4.1
   Installed ArnoldiMethod ──────── v0.2.0
   Installed NLopt ──────────────── v0.6.5
   Installed BenchmarkTools ─────── v1.3.1
   Installed PolygonOps ─────────── v0.1.2
   Installed CodecBzip2 ─────────── v0.7.2
   Installed MathOptInterface ───── v1.2.0
   Installed SpecialFunctions ───── v1.8.4
   Installed IfElse ─────────────── v0.1.1
   Installed PkgVersion ─────────── v0.1.1
   Installed isoband_jll ────────── v0.2.3+0
   Installed BioSymbols ─────────── v4.0.4
   Installed MathProgBase ───────── v0.7.8
   Installed Graphs ─────────────── v1.4.1
   Installed Graphics ───────────── v1.1.1
   Installed MappedArrays ───────── v0.4.1
   Installed FreeType ───────────── v4.0.0
   Installed IndexableBitVectors ── v1.0.0
   Installed PaddedViews ────────── v0.5.11
   Installed StatsAPI ───────────── v1.3.0
   Installed GridLayoutBase ─────── v0.6.5
   Installed MosaicViews ────────── v0.3.3
   Installed Automa ─────────────── v0.8.2
   Installed StatsBase ──────────── v0.33.14
   Installed Match ──────────────── v1.2.0
   Installed ColorTypes ─────────── v0.11.2
   Installed Twiddle ────────────── v1.1.2
   Installed TensorCore ─────────── v0.1.1
   Installed Plots ──────────────── v1.27.6
   Installed Isoband ────────────── v0.1.1
   Installed ImageCore ──────────── v0.9.3
   Installed FreeTypeAbstraction ── v0.9.9
   Installed Inflate ────────────── v0.1.2
   Installed Imath_jll ──────────── v3.1.2+0
   Installed PooledArrays ───────── v1.4.2
   Installed Packing ────────────── v0.4.2
   Installed ColorVectorSpace ───── v0.9.8
   Installed AbstractTrees ──────── v0.3.4
   Installed ArrayInterface ─────── v5.0.8
   Installed StackViews ─────────── v0.1.1
   Installed StringDistances ────── v0.11.2
   Installed InverseFunctions ───── v0.1.4
   Installed SimpleTraits ───────── v0.9.4
   Installed ColorBrewer ────────── v0.4.0
   Installed MeshIO ─────────────── v0.4.10
   Installed OpenEXR_jll ────────── v3.1.1+0
   Installed FASTX ──────────────── v1.2.0
   Installed NLopt_jll ──────────── v2.7.1+0
   Installed MathTeXEngine ──────── v0.2.1
   Installed StableRNGs ─────────── v0.1.2
   Installed IntervalSets ───────── v0.5.4
   Installed Latexify ───────────── v0.15.15
   Installed GLFW ───────────────── v3.4.1
   Installed MakieCore ──────────── v0.1.3
   Installed Tables ─────────────── v1.6.1
   Installed IndirectArrays ─────── v1.0.0
   Installed ShaderAbstractions ─── v0.2.9
   Installed StructArrays ───────── v0.6.7
   Installed FillArrays ─────────── v0.12.8
   Installed Animations ─────────── v0.4.1
   Installed Distributions ──────── v0.25.35
   Installed ColorSchemes ───────── v3.18.0
   Installed PhyloNetworks ──────── v0.14.2
   Installed CSV ────────────────── v0.9.11
   Installed Makie ──────────────── v0.15.3
  Downloaded artifact: isoband
  Downloaded artifact: Imath
  Downloaded artifact: OpenEXR
  Downloaded artifact: NLopt
    Building ModernGL → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/344f8896e55541e30d5ccffcbf747c98ad57ca47/build.log`
Precompiling project...
  ✗ GLMakie
  ✗ J_Space
  150 dependencies successfully precompiled in 123 seconds (87 already precompiled)
  2 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages

(J_Space) pkg> instantiate
Precompiling project...
  ✗ J_Space
  0 dependencies successfully precompiled in 26 seconds (237 already precompiled, 1 skipped during auto due to previous errors)
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package

(J_Space) pkg> instantiate
Precompiling project...
  ✗ J_Space
  0 dependencies successfully precompiled in 28 seconds (237 already precompiled, 1 skipped during auto due to previous errors)
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package

(J_Space) pkg> using J_Space
ERROR: `using` is not a recognized command. Type ? for help with available commands

julia> using J_Space
[ Info: Precompiling J_Space [fd1b0027-9d6f-49b5-97ba-2af5672b046a]
┌ Warning:     OpenGL/GLFW wasn't loaded correctly or couldn't be initialized.
│     This likely means, you're on a headless server without having OpenGL support setup correctly.
│     Have a look at the troubleshooting section in the readme:
│     https://github.com/JuliaPlots/Makie.jl/tree/master/GLMakie#troubleshooting-opengl.
└ @ GLMakie ~/.julia/packages/GLMakie/pFGSp/src/gl_backend.jl:4
ERROR: LoadError: InitError: Exception[GLFW.GLFWError(GLFW.PLATFORM_ERROR, "X11: The DISPLAY environment variable is missing"), ErrorException("glfwInit failed")]
Stacktrace:
  [1] __init__()
    @ GLFW ~/.julia/packages/GLFW/BWxfF/src/GLFW.jl:35
  [2] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:768
  [3] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:854
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1097
  [5] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1013
  [6] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:997
  [7] top-level scope
    @ ~/.julia/packages/GLMakie/pFGSp/src/gl_backend.jl:2
  [8] include(mod::Module, _path::String)
    @ Base ./Base.jl:418
  [9] include(x::String)
    @ GLMakie ~/.julia/packages/GLMakie/pFGSp/src/GLMakie.jl:1
 [10] top-level scope
    @ ~/.julia/packages/GLMakie/pFGSp/src/GLMakie.jl:36
 [11] include
    @ ./Base.jl:418 [inlined]
 [12] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1318
 [13] top-level scope
    @ none:1
 [14] eval
    @ ./boot.jl:373 [inlined]
 [15] eval(x::Expr)
    @ Base.MainInclude ./client.jl:453
 [16] top-level scope
    @ none:1
during initialization of module GLFW
in expression starting at /home/xieduo/.julia/packages/GLMakie/pFGSp/src/gl_backend.jl:1
in expression starting at /home/xieduo/.julia/packages/GLMakie/pFGSp/src/GLMakie.jl:1
ERROR: LoadError: Failed to precompile GLMakie [e9467ef8-e4e7-5192-8a1a-b1aee30e663a] to /home/xieduo/.julia/compiled/v1.7/GLMakie/jl_bEogKC.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
    @ Base ./loading.jl:1466
  [3] compilecache(pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1410
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1120
  [5] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1013
  [6] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:997
  [7] include
    @ ./Base.jl:418 [inlined]
  [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1318
  [9] top-level scope
    @ none:1
 [10] eval
    @ ./boot.jl:373 [inlined]
 [11] eval(x::Expr)
    @ Base.MainInclude ./client.jl:453
 [12] top-level scope
    @ none:1
in expression starting at /data/xieduo/software/J-Space.jl/src/J_Space.jl:5
ERROR: Failed to precompile J_Space [fd1b0027-9d6f-49b5-97ba-2af5672b046a] to /home/xieduo/.julia/compiled/v1.7/J_Space/jl_H9VpCw.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
   @ Base ./loading.jl:1466
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1410
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1120
 [5] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1013
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:997

```
Do you have any suggestions?

Best,
Duo

**Comment by Alessandro-Guidi** [comment]
Hello, we are already working to solve your problem.
We will get back to you with more details in the next few days.

Alessandro

**Comment by Alessandro-Guidi** [comment]
Where are you running it? Your problem is the same as the one mentioned in our _README_ under the "_POSSIBLE PROBLEMS_" section.
Because the GLMakie library, which uses the GPU, may give this error when using a virtual machine with Ubuntu.
I await your feedback.

Alessandro

**Comment by Alessandro-Guidi** [comment]
Hi @xieduo7 ,
I have changed the backend to plot file, now J-Space uses CairoMakie and your problem should be fixed.
I hope you will try again J-Space to give me feedback.

Alessandro

**Comment by xieduo7** [comment]
Hi @Alessandro-Guidi ,

Thank you for your work. But I have come across another issue when running the example code. I will open another [issue](https://github.com/BIMIB-DISCo/J-Space.jl/issues/4#issue-1381932260).

However, for the installation of `J_Space`, can I install it using `Pkg.add`? I have tried it but failed (by the way, I used this package under julia Version 1.7.3 and Linux version 3.10.0-1160.41.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Aug 31 14:52:47 UTC 2021 instead of a virtual machine):
```
julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.3 (2022-05-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using J_Space
ERROR: ArgumentError: Package J_Space not found in current path:
- Run `import Pkg; Pkg.add("J_Space")` to install the J_Space package.

Stacktrace:
 [1] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:967

julia> import Pkg; Pkg.add("/data/xieduo/software/J-Space.jl")
ERROR: `/data/xieduo/software/J-Space.jl` is not a valid package name. Perhaps you meant `/data/xieduo/software/J-Space`
The argument appears to be a URL or path, perhaps you meant `Pkg.add(url="...")` or `Pkg.add(path="...")`.
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Types.jl:68
  [2] check_package_name
    @ ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:128 [inlined]
  [3] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Pairs{Symbol, Base.TTY, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.TTY}}})
    @ Pkg.API ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:225
  [4] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:149
  [5] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:144
  [6] #add#27
    @ ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:142 [inlined]
  [7] add
    @ ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:142 [inlined]
  [8] #add#26
    @ ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:141 [inlined]
  [9] add(pkg::String)
    @ Pkg.API ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:141
 [10] top-level scope
    @ REPL[2]:1

julia> import Pkg; Pkg.add(path="/data/xieduo/software/J-Space.jl")
     Cloning git-repo `/data/xieduo/software/J-Space.jl`
    Updating git-repo `/data/xieduo/software/J-Space.jl`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package GraphMakie [1ecd5474]:
 GraphMakie [1ecd5474] log:
 ├─possible versions are: 0.1.0-0.4.1 or uninstalled
 ├─restricted to versions * by J_Space [fd1b0027], leaving only versions 0.1.0-0.4.1
 │ └─J_Space [fd1b0027] log:
 │   ├─possible versions are: 0.1.0 or uninstalled
 │   └─J_Space [fd1b0027] is fixed to version 0.1.0
 ├─restricted by compatibility requirements with AbstractPlotting [537997a7] to versions: 0.2.0-0.4.1 or uninstalled, leaving only versions: 0.2.0-0.4.1
 │ └─AbstractPlotting [537997a7] log:
 │   ├─possible versions are: 0.9.0-0.18.3 or uninstalled
 │   ├─restricted by compatibility requirements with PlotUtils [995b91a9] to versions: 0.9.0-0.10.6 or uninstalled
 │   │ └─PlotUtils [995b91a9] log:
 │   │   ├─possible versions are: 0.5.0-1.3.1 or uninstalled
 │   │   ├─restricted by compatibility requirements with Plots [91a5bcdd] to versions: 0.5.0-1.3.1
 │   │   │ └─Plots [91a5bcdd] log:
 │   │   │   ├─possible versions are: 0.12.1-1.33.0 or uninstalled
 │   │   │   ├─restricted to versions * by SubClonalSelection [f2909333], leaving only versions 0.12.1-1.33.0
 │   │   │   │ └─SubClonalSelection [f2909333] log:
 │   │   │   │   ├─possible versions are: 0.0.0 or uninstalled
 │   │   │   │   └─SubClonalSelection [f2909333] is fixed to version 0.0.0
 │   │   │   ├─restricted by compatibility requirements with StatsPlots [f3b207a7] to versions: 0.14.0-1.33.0
 │   │   │   │ └─StatsPlots [f3b207a7] log:
 │   │   │   │   ├─possible versions are: 0.10.0-0.15.3 or uninstalled
 │   │   │   │   ├─restricted to versions * by CanEvolve [28e55d1b], leaving only versions 0.10.0-0.15.3
 │   │   │   │   │ └─CanEvolve [28e55d1b] log:
 │   │   │   │   │   ├─possible versions are: 0.1.0 or uninstalled
 │   │   │   │   │   └─CanEvolve [28e55d1b] is fixed to version 0.1.0
 │   │   │   │   └─restricted by compatibility requirements with Plots [91a5bcdd] to versions: 0.10.0-0.14.33 or uninstalled, leaving only versions: 0.10.0-0.14.33
 │   │   │   │     └─Plots [91a5bcdd] log: see above
 │   │   │   ├─restricted by compatibility requirements with RecipesBase [3cdcf5f2] to versions: 0.12.1-0.29.9 or uninstalled, leaving only versions: 0.14.0-0.29.9
 │   │   │   │ └─RecipesBase [3cdcf5f2] log:
 │   │   │   │   ├─possible versions are: 0.4.0-1.2.1 or uninstalled
 │   │   │   │   ├─restricted by compatibility requirements with Plots [91a5bcdd] to versions: 0.4.0-1.2.1
 │   │   │   │   │ └─Plots [91a5bcdd] log: see above
 │   │   │   │   ├─restricted by compatibility requirements with StatsPlots [f3b207a7] to versions: 0.5.0-1.2.1
 │   │   │   │   │ └─StatsPlots [f3b207a7] log: see above
 │   │   │   │   └─restricted by compatibility requirements with CancerSeqSim [c7b3ebfe] to versions: 0.4.0-0.8.0, leaving only versions: 0.5.0-0.8.0
 │   │   │   │     └─CancerSeqSim [c7b3ebfe] log:
 │   │   │   │       ├─possible versions are: 0.2.0 or uninstalled
 │   │   │   │       └─restricted to versions * by SubClonalSelection [f2909333], leaving only versions 0.2.0
 │   │   │   │         └─SubClonalSelection [f2909333] log: see above
 │   │   │   └─restricted by compatibility requirements with StaticArrays [90137ffa] to versions: 0.21.0-1.33.0 or uninstalled, leaving only versions: 0.21.0-0.29.9
 │   │   │     └─StaticArrays [90137ffa] log:
 │   │   │       ├─possible versions are: 0.8.0-1.5.7 or uninstalled
 │   │   │       ├─restricted by compatibility requirements with PhyloNetworks [33ad39ac] to versions: 0.8.3-1.5.7
 │   │   │       │ └─PhyloNetworks [33ad39ac] log:
 │   │   │       │   ├─possible versions are: 0.9.0-0.15.2 or uninstalled
 │   │   │       │   └─restricted to versions * by J_Space [fd1b0027], leaving only versions 0.9.0-0.15.2
 │   │   │       │     └─J_Space [fd1b0027] log: see above
 │   │   │       └─restricted by compatibility requirements with GeometryBasics [5c1252a2] to versions: 0.12.0-1.5.7
 │   │   │         └─GeometryBasics [5c1252a2] log:
 │   │   │           ├─possible versions are: 0.1.0-0.4.4 or uninstalled
 │   │   │           └─restricted by compatibility requirements with NetworkLayout [46757867] to versions: 0.3.0-0.4.4
 │   │   │             └─NetworkLayout [46757867] log:
 │   │   │               ├─possible versions are: 0.2.0-0.4.4 or uninstalled
 │   │   │               ├─restricted to versions * by J_Space [fd1b0027], leaving only versions 0.2.0-0.4.4
 │   │   │               │ └─J_Space [fd1b0027] log: see above
 │   │   │               └─restricted by compatibility requirements with GraphMakie [1ecd5474] to versions: 0.3.0-0.4.4
 │   │   │                 └─GraphMakie [1ecd5474] log: see above
 │   │   └─restricted by compatibility requirements with Plots [91a5bcdd] to versions: 0.5.0-0.6.5
 │   │     └─Plots [91a5bcdd] log: see above
 │   └─restricted by compatibility requirements with GeometryBasics [5c1252a2] to versions: [0.9.0-0.9.27, 0.12.9-0.18.3] or uninstalled, leaving only versions: 0.9.0-0.9.27 or uninstalled
 │     └─GeometryBasics [5c1252a2] log: see above
 └─restricted by compatibility requirements with Makie [ee78f7c6] to versions: 0.1.0 or uninstalled — no versions left
   └─Makie [ee78f7c6] log:
     ├─possible versions are: 0.9.0-0.17.13 or uninstalled
     ├─restricted by compatibility requirements with PlotUtils [995b91a9] to versions: 0.9.0-0.12.0 or uninstalled
     │ └─PlotUtils [995b91a9] log: see above
     └─restricted by compatibility requirements with AbstractPlotting [537997a7] to versions: [0.9.0-0.9.6, 0.13.0-0.17.13] or uninstalled, leaving only versions: 0.9.0-0.9.6 or uninstalled
       └─AbstractPlotting [537997a7] log: see above
Stacktrace:
  [1] propagate_constraints!(graph::Pkg.Resolve.Graph, sources::Set{Int64}; log_events::Bool)
    @ Pkg.Resolve ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Resolve/graphtype.jl:1063
  [2] propagate_constraints! (repeats 2 times)
    @ ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Resolve/graphtype.jl:1000 [inlined]
  [3] simplify_graph!(graph::Pkg.Resolve.Graph, sources::Set{Int64}; clean_graph::Bool)
    @ Pkg.Resolve ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Resolve/graphtype.jl:1519
  [4] simplify_graph! (repeats 2 times)
    @ ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Resolve/graphtype.jl:1519 [inlined]
  [5] resolve_versions!(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, julia_version::VersionNumber)
    @ Pkg.Operations ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:335
  [6] targeted_resolve(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, preserve::Pkg.Types.PreserveLevel, julia_version::VersionNumber)
    @ Pkg.Operations ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1154
  [7] tiered_resolve(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, julia_version::VersionNumber)
    @ Pkg.Operations ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1139
  [8] _resolve(io::Base.TTY, env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, preserve::Pkg.Types.PreserveLevel, julia_version::VersionNumber)
    @ Pkg.Operations ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1160
  [9] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, new_git::Set{Base.UUID}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform)
    @ Pkg.Operations ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1176
 [10] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Pairs{Symbol, Base.TTY, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.TTY}}})
    @ Pkg.API ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:268
 [11] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:149
 [12] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:144
 [13] #add#26
    @ ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:141 [inlined]
 [14] add
    @ ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:141 [inlined]
 [15] add(; name::Nothing, uuid::Nothing, version::Nothing, url::Nothing, rev::Nothing, path::String, mode::Pkg.Types.PackageMode, subdir::Nothing, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:166
 [16] top-level scope
    @ REPL[3]:1
```

Best,
Duo

**Comment by Alessandro-Guidi** [comment]
Hi @xieduo7 ,

You can now install J-Space using `Pkg.add`. 
You can use `import Pkg; Pkg.add(path="path/your/local/project")` as you did or you can use URL from github:  `import Pkg; Pkg.add(url="https://github.com/BIMIB-DISCo/J-Space.jl.git")` 

For your problem, I have several suggestions, but first can I see the list of currently installed packages? You need to run `Pkg.status()`

**Comment by xieduo7** [comment]
Hi @Alessandro-Guidi ，

The packege status:
```
julia> Pkg.status()
      Status `~/.julia/environments/v1.7/Project.toml`
  [336ed68f] CSV v0.10.4
  [28e55d1b] CanEvolve v0.1.0 `https://github.com/tomouellette/CanEvolve.jl#main`
  [a93c6f00] DataFrames v0.21.8
  [31c24e10] Distributions v0.23.12
  [38e38edf] GLM v1.8.0
  [7073ff75] IJulia v1.23.3
  [91a5bcdd] Plots v0.29.9
  [2913bbd2] StatsBase v0.33.16
  [f3b207a7] StatsPlots v0.14.33
  [f2909333] SubClonalSelection v0.0.0 `https://github.com/marcjwilliams1/SubClonalSelection.jl#master`
  [9d95f2ec] TypedTables v1.4.0
```
For the installation, I still can't succeed (see code posted below). What is the Julia version you used to develop this package?  Unlike python, julia is very unstable among different versions and I always came across problems when I use a different version of julia with the package developed. Maybe you can create a **conda environment yml file** as [gatk did](https://github.com/broadinstitute/gatk/blob/master/README.md)  so that we can install this package by creating a new conda environment and install the required dependencies automatically to ensure in the same environment as yours.
```
julia> import Pkg; Pkg.add(path="/data/xieduo/software/J-Space.jl")
    Updating git-repo `/data/xieduo/software/J-Space.jl`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package GraphMakie [1ecd5474]:
 GraphMakie [1ecd5474] log:
 ├─possible versions are: 0.1.0-0.4.1 or uninstalled
 ├─restricted to versions * by J_Space [fd1b0027], leaving only versions 0.1.0-0.4.1
 │ └─J_Space [fd1b0027] log:
 │   ├─possible versions are: 0.1.0 or uninstalled
 │   └─J_Space [fd1b0027] is fixed to version 0.1.0
 ├─restricted by compatibility requirements with AbstractPlotting [537997a7] to versions: 0.2.0-0.4.1 or uninstalled, leaving only versions: 0.2.0-0.4.1
 │ └─AbstractPlotting [537997a7] log:
 │   ├─possible versions are: 0.9.0-0.18.3 or uninstalled
 │   ├─restricted by compatibility requirements with PlotUtils [995b91a9] to versions: 0.9.0-0.10.6 or uninstalled
 │   │ └─PlotUtils [995b91a9] log:
 │   │   ├─possible versions are: 0.5.0-1.3.1 or uninstalled
 │   │   ├─restricted by compatibility requirements with Plots [91a5bcdd] to versions: 0.5.0-1.3.1
 │   │   │ └─Plots [91a5bcdd] log:
 │   │   │   ├─possible versions are: 0.12.1-1.33.0 or uninstalled
 │   │   │   ├─restricted to versions * by SubClonalSelection [f2909333], leaving only versions 0.12.1-1.33.0
 │   │   │   │ └─SubClonalSelection [f2909333] log:
 │   │   │   │   ├─possible versions are: 0.0.0 or uninstalled
 │   │   │   │   └─SubClonalSelection [f2909333] is fixed to version 0.0.0
 │   │   │   ├─restricted by compatibility requirements with StatsPlots [f3b207a7] to versions: 0.14.0-1.33.0
 │   │   │   │ └─StatsPlots [f3b207a7] log:
 │   │   │   │   ├─possible versions are: 0.10.0-0.15.3 or uninstalled
 │   │   │   │   ├─restricted to versions * by CanEvolve [28e55d1b], leaving only versions 0.10.0-0.15.3
 │   │   │   │   │ └─CanEvolve [28e55d1b] log:
 │   │   │   │   │   ├─possible versions are: 0.1.0 or uninstalled
 │   │   │   │   │   └─CanEvolve [28e55d1b] is fixed to version 0.1.0
 │   │   │   │   └─restricted by compatibility requirements with Plots [91a5bcdd] to versions: 0.10.0-0.14.33 or uninstalled, leaving only versions: 0.10.0-0.14.33
 │   │   │   │     └─Plots [91a5bcdd] log: see above
 │   │   │   ├─restricted by compatibility requirements with RecipesBase [3cdcf5f2] to versions: 0.12.1-0.29.9 or uninstalled, leaving only versions: 0.14.0-0.29.9
 │   │   │   │ └─RecipesBase [3cdcf5f2] log:
 │   │   │   │   ├─possible versions are: 0.4.0-1.2.1 or uninstalled
 │   │   │   │   ├─restricted by compatibility requirements with Plots [91a5bcdd] to versions: 0.4.0-1.2.1
 │   │   │   │   │ └─Plots [91a5bcdd] log: see above
 │   │   │   │   ├─restricted by compatibility requirements with StatsPlots [f3b207a7] to versions: 0.5.0-1.2.1
 │   │   │   │   │ └─StatsPlots [f3b207a7] log: see above
 │   │   │   │   └─restricted by compatibility requirements with CancerSeqSim [c7b3ebfe] to versions: 0.4.0-0.8.0, leaving only versions: 0.5.0-0.8.0
 │   │   │   │     └─CancerSeqSim [c7b3ebfe] log:
 │   │   │   │       ├─possible versions are: 0.2.0 or uninstalled
 │   │   │   │       └─restricted to versions * by SubClonalSelection [f2909333], leaving only versions 0.2.0
 │   │   │   │         └─SubClonalSelection [f2909333] log: see above
 │   │   │   └─restricted by compatibility requirements with StaticArrays [90137ffa] to versions: 0.21.0-1.33.0 or uninstalled, leaving only versions: 0.21.0-0.29.9
 │   │   │     └─StaticArrays [90137ffa] log:
 │   │   │       ├─possible versions are: 0.8.0-1.5.7 or uninstalled
 │   │   │       ├─restricted by compatibility requirements with PhyloNetworks [33ad39ac] to versions: 0.8.3-1.5.7
 │   │   │       │ └─PhyloNetworks [33ad39ac] log:
 │   │   │       │   ├─possible versions are: 0.9.0-0.15.2 or uninstalled
 │   │   │       │   └─restricted to versions * by J_Space [fd1b0027], leaving only versions 0.9.0-0.15.2
 │   │   │       │     └─J_Space [fd1b0027] log: see above
 │   │   │       └─restricted by compatibility requirements with GeometryBasics [5c1252a2] to versions: 0.12.0-1.5.7
 │   │   │         └─GeometryBasics [5c1252a2] log:
 │   │   │           ├─possible versions are: 0.1.0-0.4.4 or uninstalled
 │   │   │           └─restricted by compatibility requirements with NetworkLayout [46757867] to versions: 0.3.0-0.4.4
 │   │   │             └─NetworkLayout [46757867] log:
 │   │   │               ├─possible versions are: 0.2.0-0.4.4 or uninstalled
 │   │   │               ├─restricted to versions * by J_Space [fd1b0027], leaving only versions 0.2.0-0.4.4
 │   │   │               │ └─J_Space [fd1b0027] log: see above
 │   │   │               └─restricted by compatibility requirements with GraphMakie [1ecd5474] to versions: 0.3.0-0.4.4
 │   │   │                 └─GraphMakie [1ecd5474] log: see above
 │   │   └─restricted by compatibility requirements with Plots [91a5bcdd] to versions: 0.5.0-0.6.5
 │   │     └─Plots [91a5bcdd] log: see above
 │   └─restricted by compatibility requirements with GeometryBasics [5c1252a2] to versions: [0.9.0-0.9.27, 0.12.9-0.18.3] or uninstalled, leaving only versions: 0.9.0-0.9.27 or uninstalled
 │     └─GeometryBasics [5c1252a2] log: see above
 └─restricted by compatibility requirements with Makie [ee78f7c6] to versions: 0.1.0 or uninstalled — no versions left
   └─Makie [ee78f7c6] log:
     ├─possible versions are: 0.9.0-0.17.13 or uninstalled
     ├─restricted by compatibility requirements with PlotUtils [995b91a9] to versions: 0.9.0-0.12.0 or uninstalled
     │ └─PlotUtils [995b91a9] log: see above
     └─restricted by compatibility requirements with AbstractPlotting [537997a7] to versions: [0.9.0-0.9.6, 0.13.0-0.17.13] or uninstalled, leaving only versions: 0.9.0-0.9.6 or uninstalled
       └─AbstractPlotting [537997a7] log: see above
Stacktrace:
  [1] propagate_constraints!(graph::Pkg.Resolve.Graph, sources::Set{Int64}; log_events::Bool)
    @ Pkg.Resolve ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Resolve/graphtype.jl:1063
  [2] propagate_constraints! (repeats 2 times)
    @ ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Resolve/graphtype.jl:1000 [inlined]
  [3] simplify_graph!(graph::Pkg.Resolve.Graph, sources::Set{Int64}; clean_graph::Bool)
    @ Pkg.Resolve ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Resolve/graphtype.jl:1519
  [4] simplify_graph! (repeats 2 times)
    @ ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Resolve/graphtype.jl:1519 [inlined]
  [5] resolve_versions!(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, julia_version::VersionNumber)
    @ Pkg.Operations ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:335
  [6] targeted_resolve(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, preserve::Pkg.Types.PreserveLevel, julia_version::VersionNumber)
    @ Pkg.Operations ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1154
  [7] tiered_resolve(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, julia_version::VersionNumber)
    @ Pkg.Operations ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1139
  [8] _resolve(io::Base.TTY, env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, preserve::Pkg.Types.PreserveLevel, julia_version::VersionNumber)
    @ Pkg.Operations ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1160
  [9] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, new_git::Set{Base.UUID}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform)
    @ Pkg.Operations ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1176
 [10] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Pairs{Symbol, Base.TTY, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.TTY}}})
    @ Pkg.API ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:268
 [11] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:149
 [12] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:144
 [13] #add#26
    @ ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:141 [inlined]
 [14] add
    @ ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:141 [inlined]
 [15] add(; name::Nothing, uuid::Nothing, version::Nothing, url::Nothing, rev::Nothing, path::String, mode::Pkg.Types.PackageMode, subdir::Nothing, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API ~/software/julia-1.7.3/share/julia/stdlib/v1.7/Pkg/src/API.jl:166
 [16] top-level scope
    @ REPL[2]:1
```

Best,
Duo
